### PR TITLE
Outline for play component

### PR DESCRIPTION
**Pull request by benwaples**

### CODE REVIEW

**Review by gregmall — DISMISSED** [review]
looks good

**Review by Thomas-Stussi — DISMISSED** [review]
Good morning

**Review by gregmall — DISMISSED** [review]
approved

**Review by Thomas-Stussi — DISMISSED** [review]
It's over 25 thousand!

**Review by gregmall — APPROVED** [review]
very good

**Review by Thomas-Stussi — APPROVED** [review]
Gottem

**Pull request merged**
